### ISSUE TITLE
URL to Local Authority Identifiers broken

### ISSUE THREAD

**Issue by DsposalTom** [northernjamie/hwrc_data_standard#2]
It looks like the URL to

England
Scotland
Wales

are broken

this is new link for England - https://www.registers.service.gov.uk/registers/local-authority-eng

Scotland - https://www.registers.service.gov.uk/registers/local-authority-sct

Wales - https://www.registers.service.gov.uk/registers/principal-local-authority

The root page is https://www.registers.service.gov.uk/category/regional-and-local-government

**Comment by northernjamie** [comment]
Fixed by #3 BUT these will need changing again as the registers are going on March 15th - propose replacing with a controlled list.
